### PR TITLE
Adding a Russian translation

### PR DESCRIPTION
**Pull request by smotim**
### Overview
Translated all the lines into Russian. Did not launch the translated application due to #37

### CODE REVIEW

**Comment by Vysp3r** [comment]
Ooops you needed to replace the dash by an underscore.

**Comment by Vysp3r** [comment]
I don't know if it will work with a dash

**Comment by Vysp3r** [comment]
Since I can't reproduce on my system your problem would you be inclined to use the debug feature of GNOME Builder so we can pin point the cause of the problem?

**Comment by Vysp3r** [comment]
Ooops, I meant to write that in the isssue not here

**Review by Vysp3r — APPROVED** [review]

**Comment by Vysp3r** [comment]
Was the translation working on your computer?

**Comment by smotim** [comment]
изображение
Most of the app is back in English in the latest versions. Please help me figure out how to fix it.

**Comment by Vysp3r** [comment]
Just to makre sure, are you using 0.3.3?

**Comment by smotim** [comment]
Yes. This problem exists both in 0.3.2 and in the new 0.3.3. I don't remember about the previous ones

**Comment by Vysp3r** [comment]
Knowing if it was working in 0.3.1 would be really useful. Would you be able to test this version https://github.com/Vysp3r/ProtonPlus/tree/v0.3.1 using Builder and tell me if that's working in that version.

**Comment by Vysp3r** [comment]
Looks like you're not active anymore, but someone found the problem with the translation. The update should be done by the end of this weekend.

**Comment by smotim** [comment]
Thanks. Did I understand correctly that some of the lines are now specifically left only in English in all translations?
изображение

**Comment by Vysp3r** [comment]
I may have forgotten to add a file in the POTFILES file which disabled those lines. I'll make sure they're there for the next update.

**Comment by Vysp3r** [comment]
I fixed those missing translations in the dev branch. I will push an update this weekend.

**Pull request merged**
